### ISSUE TITLE
responsive web version

### ISSUE THREAD

**Issue by bobinson** [Fayiz-A/covibot#4]
A responsive web version of the application that works reasonably well in Google Chrome and Firefox will help people to access easily

**Comment by Fayiz-A** [comment]
hi @bobinson Thanks for opening the issue. Was just working on that.

**Comment by Fayiz-A** [comment]
@bobinson . Published the app on [this link](https://fayiz-a.github.io/covibot/)

**Comment by Fayiz-A** [comment]
Closing this issue as the website has been published Alhamdulillah.

**Comment by bobinson** [comment]
Thank you @Fayiz-A. The bot looks very useful.
